### ISSUE TITLE
bugs in the set_parent_function in src/netlist/module.cpp

### ISSUE THREAD

**Issue by FabianAlbertRub** [emsec/hal#162]
Some small bugs in `bool module::set_parent_module(const std::shared_ptr<module>& new_parent)`:
1. Consider lines 52 ff:
```
   if (new_parent == m_parent)
       {
           log_error("module", "can not set module as its own parent");
           return false;
       }
```
Shouldn't it be something like `if (new_parent == this) {...}`?

2. The function does not check if `new_parent` is a `nullptr`.
3. `new_parent` may not be part of the netlist (a deleted module or from another netlist) (maybe not that critical ;) )

**Comment by Slowpoke42** [comment]
Hey, good find.
1. Seems to be kind of a semi bug. I mean it's technically not wrong to check if the new parent is equal to the current parent, because you can just immediately return in that case and don't need to waste any time on further instructions but you're obviously right that the intended check here is new_parent == this.

Personally I can not see a use case for setting a modules parent to its current parent, so I would probably keep the current check aswell to prevent the sending of "useless" events, but thats a minor detail.
