### ISSUE TITLE
Graph algorithm cannot be used

### ISSUE THREAD

**Issue by ghyghy123** [emsec/hal#558]
![image](https://github.com/emsec/hal/assets/58417169/a3dd361e-6952-474a-b22f-8e316489f4d4)
Hello, I'm using the sample provided in the graph algorithm, but it says "AttributeError: 'NoneType' object has no attribute 'get_strongly_connected_components' ", I have successfully installed graph algorithm pluging and igraph, is there a solution? Thank you.

**Comment by RenWal** [comment]
I can't reproduce this issue. Usually if you get `None` from `get_plugin_instance`, this means that the plugin you've asked for is not available. Please confirm that `graph_algorithm` is available in the [Plugin Manager](https://github.com/emsec/hal/wiki/Plugin-Management), and that the plugin is loaded.

**Comment by Av0cat0** [comment]
> I can't reproduce this issue. Usually if you get `None` from `get_plugin_instance`, this means that the plugin you've asked for is not available. Please confirm that `graph_algorithm` is available in the [Plugin Manager](https://github.com/emsec/hal/wiki/Plugin-Management), and that the plugin is loaded.

I'm having this issue too, I checked the plugin manager and I couldn't find it there:
![image](https://github.com/emsec/hal/assets/75830242/333e13ff-114f-4414-bf5a-cc5060c287b4)
However, I couldn't find how to load the graph_algorithm plugin

**Comment by RenWal** [comment]
If the plugin is not visible in the plugin manager, then it does not exist in your installation. This is usually due to build options that have disabled this plugin at compile time. See also [this issue comment](https://github.com/emsec/hal/issues/528#issuecomment-1688568231), [the build options documentation](https://github.com/emsec/hal/wiki/Building-HAL#cmake-options) and [the graph algorithms documentation](https://github.com/emsec/hal/wiki/Graph-Algorithms).

Try rebuilding HAL with the `-DPL_GRAPH_ALGORITHM=1` CMake option and see if the plugin shows up.
