### ISSUE TITLE
Prompt before closing with unsaved changes

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#68]
One can currently simply close the HAL main window with an unsaved netlist and/or unsaved python script, discarding those changes. There should be a warning message before actually quitting and discarding unsaved files.

**Comment by RenWal** [comment]
Fixed in #91

**Comment by dertob** [comment]
Although the code itself is present, the closing prompt for unsaved python scripts does not appear due to the current development of the branch feature/python_editor_tabs which adds functionality to check if python files have been modified. I suggest reopening the issue to indicate that's the case and close it after the python tabs have been integrated.
