### ISSUE TITLE
Naming of insertion methods in Python class "module" inconsistent

### ISSUE THREAD

**Issue by RenWal** [emsec/hal#85]
The Python class "module" contains the methods `insert_gate` and `add_net`. This is unintuitive, so I suggest renaming one of the two methods.

**Comment by Slowpoke42** [comment]
Since the latest rework module membership is no longer optional. Every gate / net is part of one and only one module at all times. Inserting a gate / net into a module is consequently synonymous with removing it somewhere else. The current interface does not communicate this behavior to the user. Maybe a different verb like "move" or "relocate" would be more fitting.

**Comment by swallat** [comment]
@Slowpoke42 I think `move_gate` and `move_net` would be good. @devhoffmann What do you think?

**Comment by devhoffmann** [comment]
I suggest going for `assign`

**Comment by swallat** [comment]
Hm, `assign` is better. It makes sure that we add the net or gate to the current module. `move` alone does not make clear where we move the gate or net.
